language: android
jdk:
  - oraclejdk8
android:
 components:
 - tools
 - tools
 - platform-tools
 - build-tools-25.0.1
 - android-25
 - extra-android-m2repository
  - sys-img-armeabi-v7a-google_apis-25
before_script:
 - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
 - unzip gradle-2.14.1-bin.zip
 - export GRADLE_HOME=$PWD/gradle-2.14.1
 - export PATH=$GRADLE_HOME/bin:$PATH

 - echo yes | android create avd --force -n test -t android-25 --abi armeabi-v7a
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &
script:
 - gradle build connectedCheck
