language: android
jdk:
  - oraclejdk8
android:
 components:
 - tools
 - tools
 - platform-tools
 - build-tools-25.0.1
 - android-25
 - extra-android-m2repository
before_script:
 - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
 - unzip gradle-2.10-bin.zip
 - export GRADLE_HOME=$PWD/gradle-2.14.1
 - export PATH=$GRADLE_HOME/bin:$PATH
script:
 - gradle build connectedCheck
