language: android
android:
 components:
 - tools
 - tools
 - platform-tools
 - build-tools-25.0.1
 - android-25
 - extra-android-m2repository
before_script:
  - emulator -avd test -no-audio -no-window 
  - android-wait-for-emulator
  - adb shell input keyevent 82 
script:
 - ./gradlew  build connectedCheck
 - emulator -avd test -no-skin -no-audio -no-window 
 - android-wait-for-emulator
 - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
 - ./gradlew connectedCheck